GET http://localhost:3001/courses/1/progress HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJhdmF0YXJfaWQiOjEsImF2YXRhcl9wYXRoIjoiL2ltYWdlcy9hdmF0YXJzL2RvZy5wbmciLCJpYXQiOjE3ODE5Mzk0MzcsImV4cCI6MTc4MjU0NDIzN30.w7J6nCjXo6cqMRFPeVjepOKNziLeo6LcsbUZoA9VYDs