GET http://localhost:3001/users/me HTTP/1.1
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlcm5hbWUiOiJNYXJ5IiwiZW1haWwiOiJtYXJ5QGdtYWlsLmNvbSIsImF2YXRhcl9pZCI6MiwiYXZhdGFyX3BhdGgiOiIvaW1hZ2VzL2F2YXRhcnMvY2F0LnBuZyIsImlhdCI6MTc4Nzg0NzAwNiwiZXhwIjoxNzkwNDM5MDA2fQ.L74XXAD-0fC2DFJnhv0o4PVrnKBJot5RURnzrwG2VdQ