GET http://localhost:3001/users/3 HTTP/1.1
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJNYXJ5IiwiZW1haWwiOiJtYXJ5QGdtYWlsLmNvbSIsImF2YXRhcl9pZCI6MiwiYXZhdGFyX3BhdGgiOiIvaW1hZ2VzL2F2YXRhcnMvY2F0LnBuZyIsImlhdCI6MTc4MTUzMTIyNCwiZXhwIjoxNzgyMTM2MDI0fQ.9Zr9SDqmLN0rPUGWjS0tZQuPnHZYADsEVghf0ExOykc