GET http://localhost:3001/progress HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJhdmF0YXJfaWQiOjYsImF2YXRhcl9wYXRoIjoiL2ltYWdlcy9hdmF0YXJzL2ZveC5wbmciLCJpYXQiOjE3ODQwNDkwNjAsImV4cCI6MTc4NDY1Mzg2MH0.p8Zl32fdQyjtaP6mo9wYZcY03kw0AXOdDbBgDbYOVHg