GET http://localhost:3001/sentences HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJJcmVuIiwiZW1haWwiOiJpcmVuc3VsYTE5QGdtYWlsLmNvbSIsImF2YXRhcl9pZCI6MSwiYXZhdGFyX3BhdGgiOiIvaW1hZ2VzL2F2YXRhcnMvZG9nLnBuZyIsImlhdCI6MTc4OTM3NTg0MSwiZXhwIjoxNzkxOTY3ODQxfQ.SDniikdf7_0OjaPwPFUCvJX1A9bHNFYVkZ9qC0z8bfE